### ISSUE TITLE
Using `\verb` in awesomeboxes now fails

### ISSUE THREAD

**Issue by vigou3** [milouse/latex-awesomebox#12]
With awesomebox v0.2 shipping with TeX Live 2018, usage of `\verb` was allowed in admonition boxes. With v0.5 in TeX Live 2019, this is no longer the case. MWE compiling fine in TL 2018, but not in TL 2019:

```
\documentclass{article}
  \usepackage{awesomebox}

\begin{document}

\notebox{The symbol \verb|~| identifies the user home directory.}

\end{document}
```

The behavior change may have happened between the two above revisions, I didn't check. What I did notice, though, is that v0.5 now uses package **array** instead of **tabularx**.

**Comment by milouse** [comment]
Thanks for your issues. I think both are effectively due to the move to array. I'll try to find time to investigate on them.

**Comment by milouse** [comment]
For this one, as a workaround for now, you can safely use the new environment commands:

```latex
\documentclass{article}
\usepackage{awesomebox}

\begin{document}

\begin{noteblock}
  The symbol \verb|~| identifies the user home directory.
\end{noteblock}

\end{document}
```

**Comment by milouse** [comment]
I can confirm this is due to the underlying tabular. You'll find here other workaround to insert verbatim fragments in awesome box/block: https://tex.stackexchange.com/questions/472706/how-to-use-verb-in-the-environment-tabular

As the environment approach works, I won't try further to actually fixing it. I'll just add a note in the manual in the « breaking changes » section to let users know about that.

**Comment by vigou3** [comment]
All right for me!
