### ISSUE TITLE
Footnotes in an awesomebox not showing up

### ISSUE THREAD

**Issue by jchampavere** [milouse/latex-awesomebox#14]
Footnotes defined in environments from awesomebox package are not showing up, as in the MWE below.

```
\documentclass[english]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{lmodern}
\usepackage[a4paper]{geometry}
\usepackage{awesomebox}
\usepackage{babel}
\begin{document}
\begin{noteblock}
I can't get a \verb|\footnote|!\footnote{Can I?}
\end{noteblock}
\end{document}
```
I've also posted the issue as a question in LaTeX Stack Exchange (https://tex.stackexchange.com/questions/504154/how-can-i-get-footnotes-in-awesomebox)

**Comment by milouse** [comment]
Hi,

Your problem comes from the fact that awesomebox use a tabular environment to create its boxes. Thus you have the same problem as [this one](https://tex.stackexchange.com/questions/109467/footnote-in-tabular-environment).

To have footnotes working, you just have to add the following lines in your document header:

```latex
\usepackage{footnote}
\makesavenoteenv{tabular}
```

I'll add information about that in the package documentation for a future release. Thank you very much for your bug report.

I keep it open to remind me about adding documentation.

**Comment by jchampavere** [comment]
Thanks for the quick answer and the trick, which solves my issue.

**Comment by milouse** [comment]
Documentation added. This not worses a new release thought, but at least it's commited and will be published with next release.
